### ISSUE TITLE
code does not produce cubic spline

### ISSUE THREAD

**Issue by achan001** [tomer953/cubic-spline#1]
```
>>> run_example([(1,0),(2,1),(3,0),(4,1),(5,0)])
points:
(1.0,0.0)
(2.0,1.0)
(3.0,0.0)
(4.0,1.0)
(5.0,0.0)

Cubic spline interpolation:
[1.0,2.0] f(x) = -0.5(x-1.0)^3 + 1.5(x-1.0)
[2.0,3.0] f(x) = 1.0(x-2.0)^3 - 1.5(x-2.0)^2 - 0.5(x-2.0) + 1.0
[3.0,4.0] f(x) = -1.0(x-3.0)^3 + 1.5(x-3.0)^2 + 0.5(x-3.0)
[4.0,5.0] f(x) = 0.5(x-4.0)^3 - 1.5(x-4.0)^2 + 1.0
```
Above is not cubic spline, which required continuous f, f', f''
Based on above output, slope is not continuous.

[1.0,2.0] f'(x) = -1.5*(x-1)^2 + 1.5
[2.0,3.0] f'(x) = 3*(x-2)^2 - 3*(x-2.0) - 0.5

f'(2-ε) = -1.5 + 1.5 = 0
f'(2+ε) = -0.5

Correct cubic spline can be obtained from online calculator.
https://tools.timodenk.com/?p=cubic-spline-interpolation

**Comment by tomer953** [comment]
Hi. 

Thanks for your reply. 
this repo was used for an academic assignment. 
I used the following article for building the code:

https://www.math.ntnu.no/emner/TMA4215/2008h/cubicsplines.pdf

Please try to follow the example in this presentation and see if it makes sense to you. 
if not ill glad if you can point the error of make a PR. 

Thanks 🙏

**Comment by achan001** [comment]
The article example has only 2x2 matrix.
For general case, it required **Gaussian Elimination** steps.
This may explain your simple example (2 intervals) work, but not the other.

Also, do not totally trust the article, unless we checked edge cases.
(say, uneven intervals, higher dimensional matrix)

**Comment by achan001** [comment]
OP example, solved by XCAS **spline** command.
Internally, **spline** build the constraints, then call **linsolve**
```
XCAS> X,Y := [1,2,3,4,5], [0,1,0,1,0]
XCAS> f := spline(X,Y)
XCAS> map(f, e2r) // cubic coefs

 [[ -5/7,  15/7,   -3/7,     -1],
  [ 11/7, -81/7,     27, -135/7],
  [-11/7, 117/7, -405/7,  459/7],
  [  5/7, -75/7,  363/7, -565/7]]
```

Above f is true natural cubic-spline.
Example, for x=2, we have continuous f, f', f''
```
XCAS> f[:2](x=2)    --> [1, 1]
XCAS> f[:2]'(x=2)   --> [-3/7, -3/7]
XCAS> f[:2]''(x=2)  --> [-30/7, -30/7]
```
